const words = [
  {
    letra: "A",
    palabra: "Algoritmo",
    palabra2: "Diagrama",
    descripcion:
      "conjunto de instrucciones o reglas definidas que permiten solucionar un problema ",
    descripcion2:
      "diseño geométrico que se realiza con el objetivo de representar gráficamente ideas o soluciones",
    empieza: true,
    contiene: false,
    empieza2: false,
    contiene2: true,
  },
  {
    letra: "B",
    palabra: "Base de datos",
    palabra2: "Boolean",
    descripcion:
      "recopilación organizada de información o datos estructurados, que normalmente se almacena de forma electrónica en un sistema informático",
    descripcion2:
      "Tipo de variable que permite guardar datos verdaderos o falsos",
    empieza: true,
    contiene: false,
    empieza2: true,
    contiene2: false,
  },
  {
    letra: "C",
    palabra: "Contenedor",
    descripcion:
      "recuadros o espacios rectangulares que pueden colocarse en cualquier parte de la página",
    palabra2: "Char",
    descripcion2: "Tipo de variable que se usa en MYSQL para guardar una letra",
    empieza: true,
    contiene: false,
    empieza2: true,
    contiene2: false,
  },

  {
    letra: "D",
    palabra: "DER",
    palabra2: "DDL",
    descripcion:
      "herramienta de modelado de sistemas, que se concentra en los datos almacenados en el sistema y las relaciones entre éstos",
    descripcion2:
      "lenguaje para describir los datos y sus relaciones en una base de datos",
    empieza: true,
    contiene: false,
    empieza2: true,
    contiene2: false,
  },
  {
    letra: "E",
    palabra: "MER",
    palabra2: "Pasaje a tabla",
    descripcion:
      "herramienta para el modelo de datos, la cual facilita la representación de entidades de una base de datos.",
    descripcion2:
      "descriptacion de un MER para agregar datos a una tabla de entidades o relaciones",
    empieza: false,
    contiene: true,
    empieza2: false,
    contiene2: true,
  },
  {
    letra: "F",
    palabra: "Foreign key",
    palabra2: "False",
    descripcion:
      "Variable que se utiliza cuando nuestro atributo hace referencia un atributo de otra tabla",
    descripcion2:
      "Estado de un dato que se ecuentra dentro de una variable booleana",
    empieza: true,
    contiene: false,
    empieza2: true,
    contiene2: false,
  },
  {
    letra: "G",
    palabra: "Swing",
    palabra2: "Programacion",
    descripcion:
      " Su función es  proporcionar una interfaz gráfica de usuario (GUI) para programas de Java",
    descripcion2: "proceso de creación de programas informáticos",
    empieza: false,
    contiene: true,
    empieza2: false,
    contiene2: true,
  },
  {
    letra: "H",
    palabra: "HTML",
    palabra2: "varchar",
    descripcion: "lenguaje que se utiliza para la elaboracion de paginas web",
    descripcion2:
      "variable de MYSQL en la que podemos guardar cadenas de texto",
    empieza: true,
    contiene: false,
    empieza2: false,
    contiene2: true,
  },
  {
    letra: "I",
    palabra: "int",
    palabra2: "if",
    descripcion: "Variable en la que podemos almacenar números enteros",
    descripcion2: " Estructura de control utilizada para tomar decisiones",
    empieza: true,
    contiene: false,
    empieza2: true,
    contiene2: false,
  },
  {
    letra: "J",
    palabra: "Javascript",
    palabra2: "Java Project",
    descripcion: "Lenguaje de programación",
    descripcion2: "Proyecto que creamos cuando utilizamos Eclypse",
    empieza: true,
    contiene: false,
    empieza2: true,
    contiene2: false,
  },
  {
    letra: "L",
    palabra: "Visual Studio Code",
    palabra2: "Eclypse",
    descripcion: "Programa que se utiliza para desarrollar",
    descripcion2: "Programa que se utiliza para codear",
    empieza: false,
    contiene: true,
    empieza2: false,
    contiene2: true,
  },
  {
    letra: "M",
    palabra: "Free code camp",
    palabra2: "UML",
    descripcion:
      " plataforma web de enseñanza interactiva accesible para todo el mundo,que se basa en la enseñanza del desarrollo web",
    descripcion2:
      " lenguaje gráfico para visualizar, especificar, construir y documentar un sistema ",
    empieza: false,
    contiene: true,
    empieza2: false,
    contiene2: true,
  },

  {
    letra: "N",
    palabra: "background-color",
    palabra2: " Input",
    descripcion:
      "Codigo que se utiliza para darle color  al fondo de nuestra pagina web",
    descripcion2: "Entrada de datos",
    empieza: false,
    contiene: true,
    empieza2: false,
    contiene2: true,
  },
  {
    letra: "Ñ",
    palabra: "Diseño web",
    descripcion: "",
    descripcion2: "",
    empieza: false,
    contiene: false,
    empieza2: false,
    contiene2: false,
  },
  {
    letra: "O",
    palabra: "Bootstrap",
    palabra2: "Button",
    descripcion:
      "biblioteca multiplataforma o conjunto de herramientas de  código abierto para diseño de sitios y aplicaciones web",
    descripcion2:
      "linea de codigo que te permite un acción de un pulsador en la web",
    empieza: false,
    contiene: true,
    empieza2: false,
    contiene2: true,
  },

  {
    letra: "P",
    palabra: "Primary key",
    palabra2: "Apis",
    descripcion: "LFSDLFKJSD",
    empieza: false,
    contiene: false,
  },
  {
    letra: "R",
    palabra: "Atributo primo",
    palabra2: "src",
    descripcion: "LFSDLFKJSD",
    empieza: false,
    contiene: false,
  },
  {
    letra: "S",
    palabra: "Sintaxis",
    palabra2: "CSS",
    descripcion: "LFSDLFKJSD",
    empieza: false,
    contiene: false,
  },
  {
    letra: "T",
    palabra: "Title",
    palabra2: "Output",
    descripcion: "Es lo primero que ves cuando ingresas a una página web",
    descripcion2: "Salida de datos",
    empieza: true,
    contiene: false,
    empieza2: false,
    contiene2: true,
  },
  {
    letra: "U",
    palabra: "return",
    palabra2: "url",
    descripcion: "LFSDLFKJSD",
    empieza: false,
    contiene: false,
  },
  {
    letra: "V",
    palabra: "Var",
    palabra2: "Div",
    descripcion: "LFSDLFKJSD",
    empieza: false,
    contiene: false,
  },
  {
    letra: "X",
    palabra: "hola",
    descripcion: "LFSDLFKJSD",
    empieza: false,
    contiene: false,
  },
  {
    letra: "Y",
    palabra: "Body",
    palabra2: "Type",
    descripcion: "Cuerpo de la pagina web",
    descripcion2: "Variable que usamos para poner un tipo de dato",
    empieza: false,
    contiene: true,
    empieza2: false,
    contiene2: true,
  },
  {
    letra: "Z",
    palabra: "hola",
    descripcion: "LFSDLFKJSD",
    empieza: false,
    contiene: false,
  },
];

export { words };